carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

publiccart/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('adminsecurelogin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),

    # orders urls
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review')
] 

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count


class Products(models.Model):
    objects = None
    product_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])

        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = float(reviews['count'])

        return count


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'color'),
    ('size', 'size')
)


class Variation(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    DoesNotExist = None
    objects = None
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    objects = None
    product = models.ForeignKey(Products, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to='store/products/', max_length=255)

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product Gallery'

    def __str__(self):
        return self.product.product_name

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Products, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse


def _cart_id(request):  # private function
    # taking session_id as a cart_id
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Products.objects.get(id=product_id)  # this will get the product
    # if the user is authenticated or not
    if current_user.is_authenticated:
        product_variation = []

        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            existing_variations_list = []
            id = []
            for item in cart_item:
                existing_variations = item.variations.all()
                existing_variations_list.append(list(existing_variations))
                id.append(item.id)

            if product_variation in existing_variations_list:
                # increase the cart_item quantity
                index = existing_variations_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # create a new cart _tem
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()

        return redirect('cart')

    # If the user is not authenticated
    else:
        product_variation = []

        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # get the cart using the cart_id present in the session

        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
            cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            existing_variations_list = []
            id = []
            for item in cart_item:
                existing_variations = item.variations.all()
                existing_variations_list.append(list(existing_variations))
                id.append(item.id)

            if product_variation in existing_variations_list:
                # increase the cart_item quantity
                index = existing_variations_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                # create a new cart _tem
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()

        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Products, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass

    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Products, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()

    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total

    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass  # just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total

    }
    return render(request, 'store/checkout.html', context)
 

store/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist

from carts.models import CartItem
from carts.views import _cart_id
from category.models import Category
from .models import Products, ReviewRating, ProductGallery
from .forms import ReviewForm
from orders.models import OrderProduct


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)

        products = Products.objects.filter(
            category=categories, is_available=True)

        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

    else:
        products = Products.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

    product_count = products.count()
    context = {
        'products': paged_products,
        'product_count': product_count
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Products.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()

        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct': orderproduct,
        'reviews': reviews,
        'product_gallery': product_gallery
    }
    return render(request, 'store/product_detail.html', context)


def search(request):
    products = None
    product_count = None
    keyword = None
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Products.objects.order_by('-created_date').filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword)
            )

            product_count = products.count()

    context = {
        'keyword': keyword,
        'products': products,
        'product_count': product_count
    }
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank You! Your Review has been updated.')

            return redirect(url)

        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank You! Your Review has been submitted.')

                return redirect(url)

templates/store/product_detail.html
{% extends 'base.html' %} {% block content %} {% load static %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <center>
                <img src="{{ single_product.images.url }}" />
              </center>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <ul class="thumb">
            <li>
              <a href="{{ single_product.images.url }}" target="mainImage">
                <img src="{{ single_product.images.url }}" alt="porduct image">
              </a>
              {% for image in product_gallery %}
                <a href="{{ image.image.url }}" target="mainImage">
                  <img src="{{ image.image.url }}" alt="porduct image">
                </a>
              {% endfor %}
              
            </li>
          </ul>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{ single_product.product_name }}</h2>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if single_product.averageReview < 0.5%}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1%}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 1.5%}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2%}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 2.5%}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3%}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 3.5%}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4%}-half-o{% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 4.5%}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5%}-half-o{% endif %}" aria-hidden="true"></i>
                </span>
                <span>{{ single_product.countReview}} reviews</span>
              </div>

              <div class="mb-3">
                <var class="price h4">${{ single_product.price }}</var>
              </div>

              <p>{{ single_product.description }}</p>

              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                  <select name="color" class="form-control" required>
                    <option value="" disabled selected>Select Color</option>
                    {% for i in single_product.variation_set.colors %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <select name="size" class="form-control" required>
                    <option value="" disabled selected>Select Sizes</option>
                    {% for i in single_product.variation_set.sizes %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %}
              <h5 class="text-danger">Out of Stock</h5>
              {% else %} {% if in_cart %}
                <button
                  type="submit"
                  class="btn btn-primary"
                >
                  <span class="text">Add to Cart</span>
                  <i class="fas fa-shopping-cart"></i>
                </button>
                <a href="#" class="btn btn-success">
                  <span class="text">Added to Cart</span>
                  <i class="fas fa-check"></i>
                </a>
                <a href="{% url 'cart' %}" class="btn btn-outline-primary">
                  <span class="text">View Cart</span>
                  <i class="fas fa-shopping-cart"></i>
                </a>
              {% else %}
              <button
                type="submit"
                class="btn btn-primary"
              >
                <span class="text">Add to Cart</span>
                <i class="fas fa-shopping-cart"></i>
              </button>
              {% endif %} {% endif %}
            </article>
          </form>
          <!-- product-info-aside .// -->
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        
        <form action="{% url 'submit_review' single_product.id %}" method="POST">
          {% csrf_token %}
          <h5>Write Your Review</h5>
          <br>
          {% include 'includes/alerts.html' %}
          <div>
            <!-- Rating stars -->
            <label for="">How do you rate the product?</label>
            
            <br>
            <div class="rate">
              <input type="radio" name="rating" id="rating10" value="5" required> <label for="rating10" title="5"></label>
              <input type="radio" name="rating" id="rating9" value="4.5" required> <label for="rating9" title="4.5" class="half"></label>
              <input type="radio" name="rating" id="rating8" value="4" required> <label for="rating8" title="4"></label>
              <input type="radio" name="rating" id="rating7" value="3.5" required> <label for="rating7" title="3.5" class="half"></label>
              <input type="radio" name="rating" id="rating6" value="3" required> <label for="rating6" title="3"></label>
              <input type="radio" name="rating" id="rating5" value="2.5" required> <label for="rating5" title="2.5" class="half"></label>
              <input type="radio" name="rating" id="rating4" value="2" required> <label for="rating4" title="2"></label>
              <input type="radio" name="rating" id="rating3" value="1.5" required> <label for="rating3" title="1.5" class="half"></label>
              <input type="radio" name="rating" id="rating2" value="1" required> <label for="rating2" title="1"></label>
              <input type="radio" name="rating" id="rating1" value="0.5" required> <label for="rating0" title="0.5" class="half"></label>
            </div>
            <br>
            Review Title: *
            <input type="text" class="form-control" name="subject">
            <br>
            Review:
            <textarea name="review" rows="5" class="form-control"></textarea>
            <br>
            {% if user.is_authenticated %}
              {% if orderproduct %}
                <input type="submit" value="Submit Review" class="btn btn-primary">
              {% else %}
              <p>You have to purchase this product to post review. </p>
              {% endif%}
            {% else %}
              <p>You must be logged in to post review. <span> <a href="{% url 'login' %}">Login Now</a></span> </p>
            {% endif %}
          </div>
          
        </form>
        <br>
        <header class="section-heading">
          <h3>Customer Reviews</h3>
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if single_product.averageReview < 0.5%}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1%}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 1.5%}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2%}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 2.5%}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3%}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 3.5%}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4%}-half-o{% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 4.5%}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5%}-half-o{% endif %}" aria-hidden="true"></i>
            </span>
            <span>{{ single_product.countReview}} reviews</span>
          </div>
        </header>

        {% for review in reviews %}
          <article class="box mb-3">
            <div class="icontext w-100">
              <img
                src="{% static './images/avatars/avatar1.jpg' %}"
                class="img-xs icon rounded-circle"
              />
              <div class="text">
                <span class="date text-muted float-md-right">{{ review.updated_at }} </span>
                <h6 class="mb-1">{{ review.user.full_name }}</h6>
                <div class="rating-star">
                  <span>
                    <i class="fa fa-star{% if review.rating == 0.5%}-half-o{% elif review.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 1.5%}-half-o{% elif review.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 2.5%}-half-o{% elif review.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 3.5%}-half-o{% elif review.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if review.rating == 4.5%}-half-o{% elif review.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>
                  </span>
                </div>
              </div>
            </div>
            <!-- icontext.// -->
            <div class="mt-3">
              <h5>{{ review.subject }}</h5>
              <p>
                {{ review.review }}
              </p>
            </div>
          </article>
        {% endfor %}
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}